name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
     - main
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a GitHub release
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Draft release
        uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449  # 7.3.1
        with:
          config-name: release-drafter/config.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 1
